"""
Plataforma de Protección de Datos — API y servidor web.

Ejecutar: uvicorn backend.app:app --host 0.0.0.0 --port 8000
Variables: DATABASE_URL (Postgres), DATA_DIR (archivos, default ./data), ADMIN_PASSWORD (solo para el
primer arranque), MAX_UPLOAD_MB (200).
"""
from __future__ import annotations

import csv
import hashlib
import hmac
import io
import json
import logging
import os
import secrets
import tempfile
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path

import psycopg
from fastapi import Depends, FastAPI, File, Form, HTTPException, Request, Response, UploadFile
from fastapi.responses import FileResponse, JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from psycopg.rows import dict_row
from starlette.background import BackgroundTask

from . import engine, pipeline

APP_VERSION = "0.6.0"
ROLES = ("regular", "operador", "revisor", "aprobador", "auditor", "administrador")
UTC_MINUS_3 = timezone(timedelta(hours=-3))
DATA_DIR = Path(os.environ.get("DATA_DIR", "data")).resolve()
DATA_DIR.mkdir(parents=True, exist_ok=True)
DATABASE_URL = os.environ.get("DATABASE_URL", "")
MAX_UPLOAD = int(os.environ.get("MAX_UPLOAD_MB", "200")) * 1024 * 1024
SESSION_TTL = 8 * 3600

app = FastAPI(title="Plataforma de Protección de Datos — SUBTEL", version=APP_VERSION,
              docs_url="/docs", openapi_url="/openapi.json")


# ---------------------------------------------------------------------------
# Base de datos (PostgreSQL)
# ---------------------------------------------------------------------------

class Connection(psycopg.Connection):
    """Conexión Postgres que acepta los placeholders `?` del código y devuelve filas dict."""

    def execute(self, query, params=None, **kw):
        return super().execute(query.replace("?", "%s") if isinstance(query, str) else query, params, **kw)


def db() -> Connection:
    # Cada operación abre su propia conexión; no se comparten conexiones entre hilos.
    if not DATABASE_URL:
        raise RuntimeError("Configure DATABASE_URL con la conexión a PostgreSQL de este ambiente")
    return Connection.connect(DATABASE_URL, row_factory=dict_row, connect_timeout=10)


# Claves de pg_advisory_xact_lock: serializan lo que antes serializaba BEGIN IMMEDIATE de SQLite.
LOCK_SCHEMA, LOCK_AUDIT = 7001, 7002

SCHEMA = """
CREATE TABLE IF NOT EXISTS users(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE NOT NULL, display_name TEXT NOT NULL,
  role TEXT NOT NULL, password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1,
  auth_source TEXT NOT NULL DEFAULT 'local', created_at TEXT NOT NULL, last_login_at TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id BIGINT NOT NULL, expires DOUBLE PRECISION NOT NULL);
CREATE TABLE IF NOT EXISTS api_tokens(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, token_hash TEXT UNIQUE NOT NULL,
  created_by BIGINT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, last_used_at TEXT);
CREATE TABLE IF NOT EXISTS audit_log(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ts TEXT NOT NULL, username TEXT NOT NULL, ip TEXT,
  event TEXT NOT NULL, details TEXT NOT NULL, prev_hash TEXT NOT NULL, hash TEXT NOT NULL);
-- Bitácora inalterable: la app nunca hace UPDATE/DELETE/TRUNCATE aquí; los triggers lo impiden a nivel de base.
CREATE OR REPLACE FUNCTION audit_inalterable() RETURNS trigger LANGUAGE plpgsql AS
  $$ BEGIN RAISE EXCEPTION 'audit_log es inalterable'; END $$;
DROP TRIGGER IF EXISTS audit_no_update ON audit_log;
CREATE TRIGGER audit_no_update BEFORE UPDATE OR DELETE ON audit_log FOR EACH ROW EXECUTE FUNCTION audit_inalterable();
DROP TRIGGER IF EXISTS audit_no_truncate ON audit_log;
CREATE TRIGGER audit_no_truncate BEFORE TRUNCATE ON audit_log FOR EACH STATEMENT EXECUTE FUNCTION audit_inalterable();
CREATE TABLE IF NOT EXISTS document_types(code TEXT PRIMARY KEY, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS policies(document_type TEXT NOT NULL, entity_code TEXT NOT NULL, enabled INTEGER NOT NULL,
  PRIMARY KEY(document_type, entity_code));
CREATE TABLE IF NOT EXISTS batches(id TEXT PRIMARY KEY, name TEXT NOT NULL, document_type TEXT,
  created_by TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS documents(
  id TEXT PRIMARY KEY, batch_id TEXT, original_name TEXT NOT NULL, format TEXT NOT NULL,
  size_bytes BIGINT, sha256 TEXT, pages INTEGER, document_type TEXT, entities TEXT NOT NULL,
  treatment TEXT, analysis_level TEXT NOT NULL DEFAULT 'fast', status TEXT NOT NULL, uploaded_by TEXT NOT NULL,
  error TEXT, stats TEXT, verification TEXT, created_at TEXT NOT NULL, protected_at TEXT,
  submitted_at TEXT, submitted_by TEXT, decision_at TEXT, decision_by TEXT, decision_note TEXT);
CREATE TABLE IF NOT EXISTS findings(
  id TEXT PRIMARY KEY, document_id TEXT NOT NULL, entity_code TEXT NOT NULL, text TEXT, score DOUBLE PRECISION,
  page INTEGER, boxes TEXT, location TEXT, start_off INTEGER, end_off INTEGER,
  source TEXT NOT NULL DEFAULT 'auto', status TEXT NOT NULL DEFAULT 'accepted', reviewed_by TEXT, reviewed_at TEXT);
CREATE INDEX IF NOT EXISTS idx_documents_status ON documents(status);
CREATE INDEX IF NOT EXISTS idx_documents_batch ON documents(batch_id);
CREATE INDEX IF NOT EXISTS idx_findings_doc ON findings(document_id);
-- Trabajos masivos: bucket → cola en Postgres → bucket. Cualquier pod toma ítems con SKIP LOCKED.
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, created_by TEXT NOT NULL, options TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS job_items(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id TEXT NOT NULL, ref TEXT, name TEXT NOT NULL,
  source_url TEXT, target_url TEXT, target_headers TEXT, status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0, lease_until DOUBLE PRECISION, sha256 TEXT, stats TEXT, verification TEXT,
  error TEXT, finished_at TEXT);
CREATE INDEX IF NOT EXISTS idx_job_items_job ON job_items(job_id);
CREATE INDEX IF NOT EXISTS idx_job_items_pending ON job_items(id) WHERE status IN ('queued','processing');
CREATE TABLE IF NOT EXISTS pseudonym_aliases(
  scope_id TEXT NOT NULL, entity_code TEXT NOT NULL, value_hash TEXT NOT NULL, alias TEXT NOT NULL,
  PRIMARY KEY(scope_id, entity_code, value_hash), UNIQUE(scope_id, entity_code, alias));
"""

DOCUMENT_TYPES = [("resolucion", "Resolución"), ("decreto", "Decreto"), ("contrato", "Contrato"),
                  ("convenio", "Convenio"), ("acta", "Acta"), ("oficio", "Oficio"),
                  ("expediente", "Expediente"), ("otro", "Otro")]


def hash_password(pw: str, salt: bytes | None = None) -> str:
    salt = salt or secrets.token_bytes(16)
    h = hashlib.scrypt(pw.encode(), salt=salt, n=2 ** 14, r=8, p=1)
    return salt.hex() + "$" + h.hex()


def check_password(pw: str, stored: str) -> bool:
    if not stored or "$" not in stored:  # usuarios LDAP no tienen hash local
        return False
    salt, h = stored.split("$")
    return hmac.compare_digest(hash_password(pw, bytes.fromhex(salt)).split("$")[1], h)


def now() -> str:
    """Hora operacional solicitada por SUBTEL: offset fijo UTC-3."""
    return datetime.now(UTC_MINUS_3).isoformat(timespec="seconds")


@app.on_event("startup")
def init_db():
    with db() as con:
        # Con WEB_WORKERS>1 cada proceso arranca a la vez: el lock evita que dos CREATE choquen.
        con.execute("SELECT pg_advisory_xact_lock(?)", (LOCK_SCHEMA,))
        con.execute(SCHEMA)
        source = os.environ.get("MIGRATE_SQLITE_PATH")
        if source:
            from .migrate_sqlite import migrate_sqlite
            report = migrate_sqlite(con, Path(source))
            logging.getLogger(__name__).info(
                "SQLite migration verified: %s", {t: r["rows"] for t, r in report["tables"].items()})
        for code, name in DOCUMENT_TYPES:
            con.execute("INSERT INTO document_types(code,name) VALUES(?,?) ON CONFLICT DO NOTHING", (code, name))
        if not con.execute("SELECT 1 FROM users").fetchone():
            pw = os.environ.get("ADMIN_PASSWORD", "")
            if len(pw) < 10 or not any(c.isupper() for c in pw) or not any(c.isdigit() for c in pw):
                raise RuntimeError("Configure ADMIN_PASSWORD para la instalación inicial: mínimo 10 caracteres, una mayúscula y un número")
            con.execute("INSERT INTO users(username,display_name,role,password_hash,created_at) VALUES(?,?,?,?,?)",
                        ("admin", "Administrador", "administrador", hash_password(pw), now()))
        regular_pw = os.environ.get("REGULAR_PASSWORD", "")
        if regular_pw and not con.execute("SELECT 1 FROM users WHERE username='regular'").fetchone():
            if len(regular_pw) < 10 or not any(c.isupper() for c in regular_pw) or not any(c.isdigit() for c in regular_pw):
                raise RuntimeError("REGULAR_PASSWORD requiere mínimo 10 caracteres, una mayúscula y un número")
            con.execute(
                "INSERT INTO users(username,display_name,role,password_hash,created_at) VALUES(?,?,?,?,?)",
                ("regular", "Usuario Regular", "regular", hash_password(regular_pw), now()),
            )


# ---------------------------------------------------------------------------
# LDAP / Active Directory (FR-91): bind de servicio → búsqueda → bind del usuario.
# Fallback a usuarios locales si está deshabilitado o el usuario no existe en el directorio.
# ---------------------------------------------------------------------------

def ldap_authenticate(username: str, password: str) -> dict | None:
    if os.environ.get("LDAP_ENABLED", "").lower() not in ("1", "true", "yes") or not password:
        return None
    try:
        from ldap3 import Connection, Server
        from ldap3.utils.conv import escape_filter_chars
        server = Server(os.environ["LDAP_URL"], connect_timeout=5)
        attr = os.environ.get("LDAP_USER_ATTR", "sAMAccountName")
        with Connection(server, os.environ.get("LDAP_BIND_DN"), os.environ.get("LDAP_BIND_PASSWORD"),
                        auto_bind=True, receive_timeout=10) as c:
            c.search(os.environ["LDAP_BASE_DN"], f"({attr}={escape_filter_chars(username)})",
                     attributes=["displayName", "memberOf"])
            if not c.entries:
                return None
            entry = c.entries[0]
            dn = entry.entry_dn
            display = str(entry.displayName) if entry.displayName else username
            groups = [str(g).lower() for g in (entry.memberOf or [])]
        with Connection(server, dn, password, auto_bind=True):  # valida la contraseña
            pass
        role_map = json.loads(os.environ.get("LDAP_GROUP_ROLE_MAP", "{}"))
        role = next((r for g, r in role_map.items() if g.lower() in groups and r in ROLES), None) \
            or os.environ.get("LDAP_DEFAULT_ROLE", "")
        if role not in ROLES:
            return None  # sin grupo mapeado → sin acceso
        return {"display_name": display, "role": role}
    except KeyError as e:
        raise RuntimeError(f"LDAP_ENABLED=1 pero falta la variable {e}")
    except Exception:  # noqa: BLE001 — credencial inválida o directorio caído → fallback local
        return None


# ---------------------------------------------------------------------------
# Keycloak / OIDC: SUBTEL usa Google con Keycloak como broker y administra los roles ahí.
# Flujo authorization code + PKCE. Los roles salen de los client roles del cliente
# (resource_access.<client_id>.roles) o de los realm roles; sin OIDC_ROLE_MAP deben llamarse como ROLES.
# ---------------------------------------------------------------------------

# Si Keycloak asigna más de un rol, gana el de más privilegio.
ROLE_PRIORITY = ("administrador", "auditor", "aprobador", "revisor", "operador", "regular")
_oidc_meta_cache: dict = {}


def oidc_enabled() -> bool:
    return bool(os.environ.get("OIDC_ISSUER") and os.environ.get("OIDC_CLIENT_ID"))


def _http_json(url: str, data: dict | None = None) -> dict:
    import urllib.parse
    import urllib.request
    body = urllib.parse.urlencode(data).encode() if data is not None else None
    with urllib.request.urlopen(urllib.request.Request(url, data=body, headers={"Accept": "application/json"}),
                                timeout=10) as r:
        return json.loads(r.read())


def oidc_meta() -> dict:
    if not _oidc_meta_cache:
        _oidc_meta_cache.update(_http_json(os.environ["OIDC_ISSUER"].rstrip("/") + "/.well-known/openid-configuration"))
    return _oidc_meta_cache


def _jwt_claims(token: str) -> dict:
    import base64
    payload = token.split(".")[1]
    return json.loads(base64.urlsafe_b64decode(payload + "=" * (-len(payload) % 4)))


def oidc_user(tokens: dict, nonce: str) -> dict:
    """Valida el id_token y resuelve usuario y rol. Lanza ValueError con el motivo si no corresponde.

    Los tokens se obtienen directamente del endpoint de Keycloak por TLS en el
    flujo authorization code. Se comprueban issuer, audience, nonce y expiración;
    no se verifica localmente la firma JWT. Esta función no acepta tokens del
    navegador ni habilita tokens Bearer de Keycloak en los endpoints de la API.
    """
    client_id = os.environ["OIDC_CLIENT_ID"]
    idt = _jwt_claims(tokens["id_token"])
    aud = idt.get("aud")
    if idt.get("iss") != oidc_meta()["issuer"]:
        raise ValueError("issuer inesperado")
    if client_id not in (aud if isinstance(aud, list) else [aud]):
        raise ValueError("audience inesperada")
    if not hmac.compare_digest(str(idt.get("nonce", "")), nonce):
        raise ValueError("nonce inválido")
    if idt.get("exp", 0) < time.time():
        raise ValueError("id_token vencido")
    # Keycloak pone los roles en el access_token; se leen de ahí y, por si hay mapper, del id_token.
    roles: set[str] = set()
    for claims in (idt, _jwt_claims(tokens["access_token"]) if tokens.get("access_token") else {}):
        roles.update(claims.get("resource_access", {}).get(client_id, {}).get("roles", []))
        roles.update(claims.get("realm_access", {}).get("roles", []))
    # SUBTEL puede nombrar sus roles como quiera y tener cuantos quiera: OIDC_ROLE_MAP traduce cada uno
    # a un perfil de permisos de la plataforma, ej. {"abogado-dj": "revisor", "jefatura-dj": "aprobador"}.
    role_map = json.loads(os.environ.get("OIDC_ROLE_MAP", "{}"))
    roles = {role_map.get(r, r) for r in roles}
    role = next((r for r in ROLE_PRIORITY if r in roles), None) or os.environ.get("OIDC_DEFAULT_ROLE", "")
    if role not in ROLES:
        raise ValueError("sin rol asignado en Keycloak")
    username = (idt.get("preferred_username") or idt.get("email") or idt["sub"]).strip().lower()
    return {"username": username, "display_name": idt.get("name") or username, "role": role}


def audit(con: Connection, username: str, ip: str | None, event: str, details: dict):
    """Registra un evento en la cadena de hashes.

    El advisory lock se toma ANTES de leer el último hash, de modo que dos escritores
    concurrentes (hilos o procesos web distintos) no puedan encadenar sobre el mismo
    `prev_hash` y romper la cadena. Postgres hace esperar al segundo hasta el commit.
    """
    ts = now()
    d = json.dumps(details, ensure_ascii=False, sort_keys=True)
    con.commit()  # cierra la transacción implícita del llamador antes de abrir la propia
    con.execute("SELECT pg_advisory_xact_lock(?)", (LOCK_AUDIT,))
    prev = con.execute("SELECT hash FROM audit_log ORDER BY id DESC LIMIT 1").fetchone()
    prev_hash = prev["hash"] if prev else "0" * 64
    h = hashlib.sha256(f"{prev_hash}|{ts}|{username}|{ip}|{event}|{d}".encode()).hexdigest()
    con.execute("INSERT INTO audit_log(ts,username,ip,event,details,prev_hash,hash) VALUES(?,?,?,?,?,?,?)",
                (ts, username, ip, event, d, prev_hash, h))
    con.commit()


# ---------------------------------------------------------------------------
# Autenticación y autorización
# ---------------------------------------------------------------------------

def current_user(request: Request) -> dict:
    con = db()
    try:
        auth = request.headers.get("authorization", "")
        if auth.lower().startswith("bearer "):
            th = hashlib.sha256(auth[7:].strip().encode()).hexdigest()
            row = con.execute("SELECT t.id, t.name, u.role FROM api_tokens t JOIN users u ON u.id=t.created_by "
                              "WHERE t.token_hash=? AND t.active=1 AND u.active=1", (th,)).fetchone()
            if not row:
                raise HTTPException(401, "Token de API inválido")
            con.execute("UPDATE api_tokens SET last_used_at=? WHERE id=?", (now(), row["id"]))
            con.commit()
            return {"id": None, "username": f"api:{row['name']}", "display_name": row["name"], "role": "operador", "api": True}
        tok = request.cookies.get("session")
        if tok:
            row = con.execute("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1",
                              (tok, time.time())).fetchone()
            if row:
                return {"id": row["id"], "username": row["username"], "display_name": row["display_name"], "role": row["role"], "api": False}
        raise HTTPException(401, "No autenticado")
    finally:
        con.close()


def require(*roles):
    def dep(user: dict = Depends(current_user)):
        if roles and user["role"] not in roles:
            raise HTTPException(403, "Sin permiso para esta acción")
        return user
    return dep


def ip_of(request: Request) -> str | None:
    return request.client.host if request.client else None


@app.exception_handler(HTTPException)
async def http_error(_: Request, exc: HTTPException):
    return JSONResponse({"error": {"code": exc.status_code, "message": exc.detail}}, status_code=exc.status_code)


@app.post("/api/auth/login")
async def login(request: Request, response: Response, body: dict):
    username = body.get("username", "").strip().lower()
    con = db()
    try:
        ldap_user = ldap_authenticate(username, body.get("password", ""))
        if ldap_user:
            con.execute("INSERT INTO users(username,display_name,role,password_hash,auth_source,created_at) VALUES(?,?,?,?,?,?) "
                        "ON CONFLICT(username) DO UPDATE SET display_name=excluded.display_name, role=excluded.role",
                        (username, ldap_user["display_name"], ldap_user["role"], "", "ldap", now()))
            con.commit()
        row = con.execute("SELECT * FROM users WHERE username=? AND active=1", (username,)).fetchone()
        if not row or (not ldap_user and not check_password(body.get("password", ""), row["password_hash"])):
            audit(con, username or "?", ip_of(request), "login_failed", {})
            raise HTTPException(401, "Usuario o contraseña incorrectos")
        start_session(con, request, response, row)
        return {"username": row["username"], "display_name": row["display_name"], "role": row["role"]}
    finally:
        con.close()


def start_session(con: Connection, request: Request, response: Response, row, details: dict | None = None):
    tok = secrets.token_urlsafe(32)
    con.execute("INSERT INTO sessions VALUES(?,?,?)", (tok, row["id"], time.time() + SESSION_TTL))
    con.execute("UPDATE users SET last_login_at=? WHERE id=?", (now(), row["id"]))
    con.execute("DELETE FROM sessions WHERE expires<?", (time.time(),))
    audit(con, row["username"], ip_of(request), "login", details or {})
    response.set_cookie("session", tok, httponly=True, samesite="lax", max_age=SESSION_TTL)


def _oidc_redirect_uri(request: Request) -> str:
    # Detrás del ingress de Kubernetes la app ve http; OIDC_REDIRECT_URI fija la URL pública registrada en Keycloak.
    return os.environ.get("OIDC_REDIRECT_URI") or str(request.url_for("oidc_callback"))


@app.get("/api/auth/oidc")
async def oidc_status():
    return {"enabled": oidc_enabled(), "label": os.environ.get("OIDC_LABEL", "Ingresar con cuenta institucional")}


@app.get("/api/auth/oidc/login")
async def oidc_login(request: Request):
    import base64
    import urllib.parse
    from fastapi.responses import RedirectResponse
    if not oidc_enabled():
        raise HTTPException(404, "Keycloak no está configurado")
    state, nonce, verifier = (secrets.token_urlsafe(32) for _ in range(3))
    challenge = base64.urlsafe_b64encode(hashlib.sha256(verifier.encode()).digest()).rstrip(b"=").decode()
    q = urllib.parse.urlencode({"response_type": "code", "client_id": os.environ["OIDC_CLIENT_ID"],
                                "redirect_uri": _oidc_redirect_uri(request), "scope": "openid profile email",
                                "state": state, "nonce": nonce,
                                "code_challenge": challenge, "code_challenge_method": "S256"})
    resp = RedirectResponse(oidc_meta()["authorization_endpoint"] + "?" + q, status_code=302)
    resp.set_cookie("oidc_tx", f"{state}.{nonce}.{verifier}", httponly=True, samesite="lax", max_age=600,
                    path="/api/auth/oidc")
    return resp


@app.get("/api/auth/oidc/callback", name="oidc_callback")
async def oidc_callback(request: Request, code: str = "", state: str = "", error: str = ""):
    from fastapi.responses import RedirectResponse
    state_c, nonce, verifier = (request.cookies.get("oidc_tx", "").split(".") + ["", "", ""])[:3]
    con = db()
    try:
        try:
            if error or not code:
                raise ValueError(error or "sin código de autorización")
            if not state_c or not hmac.compare_digest(state, state_c):
                raise ValueError("state inválido")
            data = {"grant_type": "authorization_code", "code": code, "redirect_uri": _oidc_redirect_uri(request),
                    "client_id": os.environ["OIDC_CLIENT_ID"], "code_verifier": verifier}
            if os.environ.get("OIDC_CLIENT_SECRET"):
                data["client_secret"] = os.environ["OIDC_CLIENT_SECRET"]
            info = oidc_user(_http_json(oidc_meta()["token_endpoint"], data), nonce)
        except Exception as e:  # noqa: BLE001 — cualquier falla termina en la pantalla de login con el motivo auditado
            audit(con, "?", ip_of(request), "login_failed", {"origen": "keycloak", "motivo": str(e)[:200]})
            resp = RedirectResponse("/?login_error=keycloak", status_code=302)
            resp.delete_cookie("oidc_tx", path="/api/auth/oidc")
            return resp
        # El rol lo manda Keycloak en cada ingreso: un cambio hecho ahí se refleja al siguiente login.
        con.execute("INSERT INTO users(username,display_name,role,password_hash,auth_source,created_at) VALUES(?,?,?,?,?,?) "
                    "ON CONFLICT(username) DO UPDATE SET display_name=excluded.display_name, role=excluded.role",
                    (info["username"], info["display_name"], info["role"], "", "keycloak", now()))
        con.commit()
        row = con.execute("SELECT * FROM users WHERE username=?", (info["username"],)).fetchone()
        resp = RedirectResponse("/", status_code=302)
        resp.delete_cookie("oidc_tx", path="/api/auth/oidc")
        if not row["active"]:  # desactivado localmente por un administrador: manda sobre Keycloak
            audit(con, row["username"], ip_of(request), "login_failed", {"origen": "keycloak", "motivo": "usuario inactivo"})
            resp.headers["location"] = "/?login_error=inactivo"
            return resp
        start_session(con, request, resp, row, {"origen": "keycloak"})
        return resp
    finally:
        con.close()


@app.post("/api/auth/logout")
async def logout(request: Request, response: Response, user=Depends(current_user)):
    import urllib.parse
    con = db()
    con.execute("DELETE FROM sessions WHERE token=?", (request.cookies.get("session"),))
    src = con.execute("SELECT auth_source FROM users WHERE id=?", (user["id"],)).fetchone() if user["id"] else None
    audit(con, user["username"], ip_of(request), "logout", {})
    con.close()
    response.delete_cookie("session")
    out: dict = {"ok": True}
    # Sin esto, "Salir" deja viva la sesión de Keycloak y el siguiente clic vuelve a entrar sin pedir clave.
    if src and src["auth_source"] == "keycloak" and oidc_enabled() and oidc_meta().get("end_session_endpoint"):
        back = str(request.base_url) if not os.environ.get("OIDC_REDIRECT_URI") else \
            os.environ["OIDC_REDIRECT_URI"].split("/api/")[0] + "/"
        out["logout_url"] = oidc_meta()["end_session_endpoint"] + "?" + urllib.parse.urlencode(
            {"client_id": os.environ["OIDC_CLIENT_ID"], "post_logout_redirect_uri": back})
    return out


@app.get("/api/me")
async def me(user=Depends(current_user)):
    return user


@app.get("/api/health")
async def health():
    """Salud real: base de datos, cola de procesamiento, OCR, disco y workers."""
    import shutil as _shutil
    out: dict = {"status": "ok", "version": APP_VERSION, "engine": engine.ENGINE_VERSION,
                 "web_workers": int(os.environ.get("WEB_WORKERS", "1")),
                 "processing_workers": int(os.environ.get("PROCESSING_WORKERS", os.environ.get("WORKERS", "2")))}
    try:
        con = db()
        out["queue"] = {r["status"]: r["n"] for r in con.execute(
            "SELECT status, COUNT(*) n FROM documents WHERE status IN "
            "('uploaded','processing','submitted','approved','protecting') GROUP BY status")}
        out["jobs"] = {r["status"]: r["n"] for r in con.execute(
            "SELECT status, COUNT(*) n FROM job_items WHERE status IN ('queued','processing') GROUP BY status")}
        con.close()
        out["db"] = "ok"
        out["db_engine"] = "postgresql"
    except Exception as e:  # noqa: BLE001
        out["db"] = f"error: {type(e).__name__}"
        out["status"] = "degraded"
    du = _shutil.disk_usage(DATA_DIR)
    out["disk_free_mb"] = du.free // 1048576
    if du.free < int(os.environ.get("MIN_FREE_DISK_MB", "500")) * 1048576:
        out["status"] = "degraded"
        out["disk"] = "espacio insuficiente"
    out["ocr"] = "ok" if _shutil.which("tesseract") else "tesseract no encontrado"
    if out["ocr"] != "ok":
        out["status"] = "degraded"
    return JSONResponse(out, status_code=200 if out["status"] == "ok" else 503)


# ---------------------------------------------------------------------------
# Procesamiento de documentos
# ---------------------------------------------------------------------------

@app.get("/api/v1/entity-types")
async def entity_types(user=Depends(current_user)):
    return [{"code": c, "label": l} for c, l in engine.ENTITY_TYPES.items()]


def choice(value: str, options: dict[str, str], error: str) -> str:
    """Acepta el código de la API (`balanced`) o el nombre que muestra la plataforma
    (`Equilibrado`, con o sin tilde), para que un cliente de API elija lo mismo que un usuario."""
    v = (value or "").strip().lower()
    for code, label in options.items():
        if v == code or pipeline._norm_soft(v) == pipeline._norm_soft(label):
            return code
    raise HTTPException(422, error)


def resolve_options(con, document_type: str, entities: list[str], treatment: str, analysis_level: str) -> dict:
    """Valida las opciones que elige un usuario en la plataforma; sin `entities` rige la política del tipo."""
    from .documents import effective_entities  # import diferido: documents importa este módulo
    if not con.execute("SELECT 1 FROM document_types WHERE code=? AND active=1", (document_type,)).fetchone():
        raise HTTPException(400, "Tipo documental inválido")
    return {"document_type": document_type,
            "entities": [c for c in entities if c in engine.ENTITY_TYPES] or effective_entities(con, document_type),
            "treatment": choice(treatment, pipeline.TREATMENTS, "Tratamiento inválido"),
            "analysis_level": choice(analysis_level, pipeline.ANALYSIS_LEVELS, "Nivel de análisis inválido")}


def _opts(options: dict[str, str]) -> str:
    return " | ".join(f"{c} ({l})" for c, l in options.items())


ENTITIES_HELP = ("Códigos separados por coma (GET /api/v1/entity-types). Vacío = política del tipo documental.")
DOCUMENT_TYPE_HELP = "Tipo documental (GET /api/document-types); define la política de datos a buscar."
ANALYSIS_HELP = "Nivel de análisis: " + _opts(pipeline.ANALYSIS_LEVELS)


@app.post("/api/v1/redact", summary="Protege un documento y devuelve el archivo en el mismo formato",
          description="Procesamiento directo sin revisión humana. Los PDF se entregan como PDF/A-1b.")
async def redact(request: Request, file: UploadFile = File(...),
                 entities: str = Form("", description=ENTITIES_HELP),
                 document_type: str = Form("otro", description=DOCUMENT_TYPE_HELP),
                 treatment: str = Form("redact", description="Tratamiento: " + _opts(pipeline.TREATMENTS)),
                 analysis_level: str = Form("fast", description=ANALYSIS_HELP),
                 user=Depends(require("operador", "revisor", "aprobador", "administrador"))):
    con = db()
    try:
        opts = resolve_options(con, document_type, entities.split(","), treatment, analysis_level)
    finally:
        con.close()
    codes, treatment, analysis_level = opts["entities"], opts["treatment"], opts["analysis_level"]
    name = Path(file.filename or "documento").name
    ext = Path(name).suffix.lower()
    if ext not in engine.SUPPORTED:
        raise HTTPException(415, f"Formato no soportado: {ext or 'sin extensión'}")
    tmp = Path(tempfile.mkdtemp(prefix="tachado_"))
    src, dst = tmp / ("in" + ext), tmp / (Path(name).stem + "_protegido" + ext)
    size = 0
    with src.open("wb") as fh:
        while chunk := await file.read(1024 * 1024):
            size += len(chunk)
            if size > MAX_UPLOAD:
                raise HTTPException(413, f"Archivo supera el máximo de {MAX_UPLOAD // 1024 // 1024} MB")
            fh.write(chunk)
    sha = hashlib.sha256(src.read_bytes()).hexdigest()
    t0 = time.time()
    con = db()
    try:
        stats, verification = pipeline.protect(src, dst, tmp / "work", codes, treatment, analysis_level)
        if not verification["ok"]:
            raise engine.EngineError("VERIFY_FAILED", "La verificación detectó datos originales en el resultado")
    except engine.EngineError as e:
        audit(con, user["username"], ip_of(request), "process_failed",
              {"file": name, "sha256": sha, "analysis_level": analysis_level, "error": e.code})
        con.close()
        raise HTTPException(422 if e.code != "UNSUPPORTED_FORMAT" else 415, str(e))
    except Exception as e:  # noqa: BLE001
        audit(con, user["username"], ip_of(request), "process_failed",
              {"file": name, "sha256": sha, "analysis_level": analysis_level, "error": "INTERNAL"})
        con.close()
        raise HTTPException(500, f"Error al procesar el documento: {type(e).__name__}")
    stats["seconds"] = round(time.time() - t0, 2)
    stats["analysis_level"] = analysis_level
    audit(con, user["username"], ip_of(request), "protected",
          {"file": name, "sha256": sha, "entities": codes, "document_type": document_type,
           "treatment": treatment, "analysis_level": analysis_level, "stats": stats})
    con.close()
    return FileResponse(dst, filename=dst.name, media_type="application/octet-stream",
                        headers={"X-Tachado-Stats": json.dumps(stats, ensure_ascii=True)},
                        background=BackgroundTask(lambda: __import__("shutil").rmtree(tmp, ignore_errors=True)))


# ---------------------------------------------------------------------------
# Usuarios y roles (administrador)
# ---------------------------------------------------------------------------

@app.get("/api/users")
async def list_users(user=Depends(require("administrador"))):
    con = db()
    rows = [dict(r) for r in con.execute("SELECT id,username,display_name,role,active,auth_source,created_at,last_login_at FROM users ORDER BY id")]
    con.close()
    return rows


def _validate_password(pw: str):
    if len(pw) < 10 or not any(c.isupper() for c in pw) or not any(c.isdigit() for c in pw):
        raise HTTPException(400, "La contraseña debe tener al menos 10 caracteres, una mayúscula y un número")


@app.post("/api/users", status_code=201)
async def create_user(request: Request, body: dict, user=Depends(require("administrador"))):
    username = body.get("username", "").strip().lower()
    if not username.isidentifier():
        raise HTTPException(400, "Nombre de usuario inválido (letras, números y guion bajo)")
    if body.get("role") not in ROLES:
        raise HTTPException(400, "Rol inválido")
    _validate_password(body.get("password", ""))
    con = db()
    try:
        con.execute("INSERT INTO users(username,display_name,role,password_hash,created_at) VALUES(?,?,?,?,?)",
                    (username, body.get("display_name") or username, body["role"], hash_password(body["password"]), now()))
    except psycopg.errors.UniqueViolation:
        con.close()
        raise HTTPException(409, "El usuario ya existe")
    audit(con, user["username"], ip_of(request), "user_created", {"username": username, "role": body["role"]})
    con.close()
    return {"ok": True}


@app.patch("/api/users/{uid}")
async def update_user(request: Request, uid: int, body: dict, user=Depends(require("administrador"))):
    con = db()
    row = con.execute("SELECT * FROM users WHERE id=?", (uid,)).fetchone()
    if not row:
        con.close()
        raise HTTPException(404, "Usuario no existe")
    changes = {}
    if "role" in body:
        if body["role"] not in ROLES:
            raise HTTPException(400, "Rol inválido")
        con.execute("UPDATE users SET role=? WHERE id=?", (body["role"], uid)); changes["role"] = body["role"]
    if "active" in body:
        if uid == user["id"] and not body["active"]:
            raise HTTPException(400, "No puedes desactivarte a ti mismo")
        con.execute("UPDATE users SET active=? WHERE id=?", (1 if body["active"] else 0, uid)); changes["active"] = bool(body["active"])
        if not body["active"]:
            con.execute("DELETE FROM sessions WHERE user_id=?", (uid,))
    if "display_name" in body:
        con.execute("UPDATE users SET display_name=? WHERE id=?", (body["display_name"], uid)); changes["display_name"] = body["display_name"]
    if body.get("password"):
        _validate_password(body["password"])
        con.execute("UPDATE users SET password_hash=? WHERE id=?", (hash_password(body["password"]), uid)); changes["password"] = "cambiada"
    audit(con, user["username"], ip_of(request), "user_updated", {"username": row["username"], **changes})
    con.close()
    return {"ok": True}


@app.post("/api/me/password")
async def change_own_password(request: Request, body: dict, user=Depends(current_user)):
    if user["api"]:
        raise HTTPException(403, "No aplica a tokens de API")
    current, new = body.get("current", ""), body.get("password", "")
    # Doble digitación (la UI pide dos veces cada contraseña). Si un cliente de API
    # no envía las confirmaciones, se asumen iguales y el comportamiento no cambia.
    if body.get("current_confirm", current) != current:
        raise HTTPException(400, "Las dos contraseñas actuales no coinciden")
    if body.get("password_confirm", new) != new:
        raise HTTPException(400, "Las dos contraseñas nuevas no coinciden")
    con = db()
    row = con.execute("SELECT password_hash FROM users WHERE id=?", (user["id"],)).fetchone()
    if not check_password(current, row["password_hash"]):
        con.close()
        raise HTTPException(400, "Contraseña actual incorrecta")
    _validate_password(new)
    con.execute("UPDATE users SET password_hash=? WHERE id=?", (hash_password(new), user["id"]))
    audit(con, user["username"], ip_of(request), "password_changed", {})
    con.close()
    return {"ok": True}


# ---------------------------------------------------------------------------
# Tokens de API (administrador)
# ---------------------------------------------------------------------------

@app.get("/api/tokens")
async def list_tokens(user=Depends(require("administrador"))):
    con = db()
    rows = [dict(r) for r in con.execute("SELECT t.id,t.name,t.active,t.created_at,t.last_used_at,u.username AS created_by "
                                         "FROM api_tokens t JOIN users u ON u.id=t.created_by ORDER BY t.id")]
    con.close()
    return rows


@app.post("/api/tokens", status_code=201)
async def create_token(request: Request, body: dict, user=Depends(require("administrador"))):
    name = (body.get("name") or "").strip()
    if not name:
        raise HTTPException(400, "Nombre requerido")
    tok = "stk_" + secrets.token_urlsafe(32)
    con = db()
    con.execute("INSERT INTO api_tokens(name,token_hash,created_by,created_at) VALUES(?,?,?,?)",
                (name, hashlib.sha256(tok.encode()).hexdigest(), user["id"], now()))
    audit(con, user["username"], ip_of(request), "token_created", {"name": name})
    con.close()
    return {"name": name, "token": tok}  # se muestra una sola vez


@app.delete("/api/tokens/{tid}")
async def revoke_token(request: Request, tid: int, user=Depends(require("administrador"))):
    con = db()
    row = con.execute("SELECT name FROM api_tokens WHERE id=?", (tid,)).fetchone()
    if not row:
        con.close()
        raise HTTPException(404, "Token no existe")
    con.execute("UPDATE api_tokens SET active=0 WHERE id=?", (tid,))
    audit(con, user["username"], ip_of(request), "token_revoked", {"name": row["name"]})
    con.close()
    return {"ok": True}


# ---------------------------------------------------------------------------
# Bitácora (auditor / administrador)
# ---------------------------------------------------------------------------

@app.get("/api/audit")
async def get_audit(request: Request, event: str = "", username: str = "", limit: int = 500, format: str = "json",
                    user=Depends(require("auditor", "administrador"))):
    con = db()
    q, args = "SELECT * FROM audit_log WHERE 1=1", []
    if event:
        q += " AND event=?"; args.append(event)
    if username:
        q += " AND username LIKE ?"; args.append(f"%{username}%")
    q += " ORDER BY id DESC LIMIT ?"; args.append(min(limit, 5000))
    rows = [dict(r) for r in con.execute(q, args)]
    title_cache: dict[str, str | None] = {}
    analysis_cache: dict[str, str] = {}
    for row in rows:
        row["treatment"] = ""
        row["analysis_level"] = ""
        try:
            detail = json.loads(row["details"])
        except (TypeError, json.JSONDecodeError):
            continue
        if isinstance(detail, dict):
            row["treatment"] = detail.get("treatment") or (detail.get("stats") or {}).get("treatment") or ""
            row["analysis_level"] = (detail.get("analysis_level")
                                     or (detail.get("stats") or {}).get("analysis_level") or "")
        if isinstance(detail, dict) and "document_id" in detail:
            doc_id = str(detail.pop("document_id"))
            title = detail.pop("file", None)
            if not title or not row["analysis_level"]:
                if doc_id not in title_cache or doc_id not in analysis_cache:
                    found = con.execute(
                        "SELECT original_name, analysis_level FROM documents WHERE id=?", (doc_id,)
                    ).fetchone()
                    title_cache[doc_id] = found["original_name"] if found else None
                    analysis_cache[doc_id] = (found["analysis_level"] if found else "") or "fast"
            if not title:
                title = title_cache[doc_id]
            if not row["analysis_level"]:
                row["analysis_level"] = analysis_cache.get(doc_id, "")
            detail["documento"] = title or "Documento eliminado"
        if isinstance(detail, dict) and "ids" in detail and "files" in detail:
            detail.pop("ids", None)
            detail["documentos"] = detail.pop("files")
        row["details"] = json.dumps(detail, ensure_ascii=False, sort_keys=True)
    con.close()
    if format == "csv":
        buf = io.StringIO()
        w = csv.DictWriter(buf, fieldnames=["id", "ts", "username", "ip", "event", "treatment",
                                            "analysis_level", "details", "prev_hash", "hash"])
        w.writeheader(); w.writerows(rows)
        return StreamingResponse(iter([buf.getvalue()]), media_type="text/csv",
                                 headers={"Content-Disposition": "attachment; filename=bitacora.csv"})
    return rows


@app.get("/api/audit/verify")
async def verify_audit(user=Depends(require("auditor", "administrador"))):
    """Recorre la cadena de hashes y confirma que nadie alteró la bitácora."""
    con = db()
    prev = "0" * 64
    for r in con.execute("SELECT * FROM audit_log ORDER BY id"):
        expected = hashlib.sha256(f"{prev}|{r['ts']}|{r['username']}|{r['ip']}|{r['event']}|{r['details']}".encode()).hexdigest()
        if r["prev_hash"] != prev or r["hash"] != expected:
            con.close()
            return {"ok": False, "broken_at": r["id"]}
        prev = r["hash"]
    con.close()
    return {"ok": True}


# ---------------------------------------------------------------------------
# Documentos con revisión, lotes y políticas (v1.1) + frontend estático
# ---------------------------------------------------------------------------

from .documents import router as documents_router, start_maintenance  # noqa: E402  (import al final: comparte helpers de este módulo)

app.include_router(documents_router)

from .jobs import router as jobs_router, start_job_workers  # noqa: E402

app.include_router(jobs_router)


@app.on_event("startup")
def _maintenance():
    # Recupera documentos atascados tras un reinicio y arranca la limpieza por retención.
    start_maintenance()
    start_job_workers()
app.mount("/", StaticFiles(directory=str(Path(__file__).parent.parent / "frontend"), html=True), name="frontend")
